"""Collect everything the submission needs from one finished run. Owner: C.

    uv run python scripts/package_submission.py                 # -> submission/<timestamp>/
    uv run python scripts/package_submission.py --label take-3 --allow-fake

Answers the workstreams open question about shipping `registry/`: a `git bundle` (the
whole history, restorable with `git clone registry.bundle`) next to a readable `git log`
and the head hash. Also copies the event log and writes EVIDENCE.md from it.

It only reads: the registry, the log and the work folder are left as they are, and it refuses
a log that contains fake events unless --allow-fake, so a scripted run can't be shipped by accident.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

from evidence import operator_actions, registry_history, render, summarize

from harness import config
from harness.ops.events import EventLog

SUBMISSION = config.ROOT / "submission"


def package(log: Path, registry: Path, dest: Path, allow_fake: bool = False) -> list[str]:
    """Write the package into `dest` and return what was written (and what had to be left out, with the reason)."""
    events = EventLog(log).read_from(0)[0]
    runs = summarize(events)
    if (fakes := [r.run_id for r in runs if r.fake]) and not allow_fake:
        raise SystemExit(f"runs {', '.join(fakes)} contain fake events; move them aside with scripts/fresh_start.py or pass --allow-fake")
    if not runs:
        raise SystemExit(f"{log} has no runs")
    dest.mkdir(parents=True, exist_ok=False)
    notes = []

    shutil.copyfile(log, dest / "events.jsonl")
    notes.append("events.jsonl: the full event log, every plan, gap, build, test output, approval, install, call and cap hit")
    history = registry_history(registry)
    (dest / "EVIDENCE.md").write_text(render(runs, history, operator_actions(events)))
    notes.append("EVIDENCE.md: what the log shows per run, generated by scripts/evidence.py")

    if not history:
        notes.append("registry: NOT included, it has no git history (empty, missing or the fake registry)")
        return notes
    head = _git(registry, "rev-parse", "HEAD").strip()
    (dest / "registry-head.txt").write_text(head + "\n")
    (dest / "registry-git-log.txt").write_text(_git(registry, "log", "--format=%h %an %aI %s %D", "--reverse"))
    bundle = subprocess.run(["git", "-C", str(registry), "bundle", "create", str((dest / "registry.bundle").resolve()), "--all"], capture_output=True, text=True)
    if bundle.returncode:
        notes.append(f"registry.bundle: NOT created ({bundle.stderr.strip()[:200]})")
    else:
        notes.append(f"registry.bundle: the whole registry history; `git clone registry.bundle registry` restores it (head {head[:10]})")
    notes.append("registry-git-log.txt, registry-head.txt: the same history, readable without git")
    return notes


def _git(repo: Path, *args: str) -> str:
    return subprocess.run(["git", "-C", str(repo), *args], capture_output=True, text=True, check=True).stdout


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("--log", type=Path, default=config.LOG_PATH)
    p.add_argument("--registry", type=Path, default=config.REGISTRY_DIR)
    p.add_argument("--label", default="")
    p.add_argument("--allow-fake", action="store_true")
    a = p.parse_args(argv)
    dest = SUBMISSION / (datetime.now().strftime("%Y%m%d-%H%M%S") + (f"-{a.label}" if a.label else ""))
    for line in package(a.log, a.registry, dest, a.allow_fake):
        print(line)
    print(f"-> {dest}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
